name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
    - name: Build Docker image
      run: docker build -t $DOCKER_USERNAME/rinha-de-backend-2024-q1 .
      
    - name: Push Docker image
      run: docker push $DOCKER_USERNAME/rinha-de-backend-2024-q1

